spring:
  application:
    name: mysite06
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    check-template-location: true
    mode: HTML
    prefix: classpath:templates/
    suffix: .html
    encoding: UTF-8
    view-names: th/*
    cache: false
  mvc:
    static-path-pattern: assets/**
  web:
    resources:
      static-locations: [ "classpath:assets/" ]
      add-mappings: true
  main:
    allow-bean-definition-overriding: true
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.64.30:3306/webdb
    username: webdb
    password: webdb
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
  messages:
    basename: messages/message
    encoding: utf-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 10485760
      max-request-size: 104857600
      file-size-threshold: 5242880
server:
  port: 8081
  servlet:
    context-path: /mysite06
mybatis:
  config-location: classpath:mybatis/configuration.xml
logging:
  config: classpath:logback.xml