spring:
  application:
    name: mysite06
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    check-template-location: true
    mode: HTML
    prefix: classpath:templates/
    suffix: .html
    encoding: UTF-8
    view-names: th/*
    cache: false
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  web:
    resources:
      static-locations: classpath:/assets/
  main:
    allow-bean-definition-overriding: true
  aop:
    auto: true
    proxy-target-class: true
server:
  port: 8080
  servlet:
    context-path: /